name: Build PDF
env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'OpenFonts/de-resume.tex'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: de-resume.tex
          latexmk_use_xelatex: true
          working_directory: OpenFonts

      - name: Generate PNG Sample
        run: |
          sudo apt update
          sudo apt install poppler-utils
          pdftoppm -png ./OpenFonts/de-resume.pdf > de-resume.png
          mv ./OpenFonts/de-resume.pdf ./OpenFonts/deepak_sisupalan_resume.pdf
      
      - name: Setup git config
        run: |
          git config user.name "dptcs"
          git config user.email "deepak.sisupalan@mnscorp.net"
      
      - name: Commit built files
        run: |
          git add OpenFonts/deepak_sisupalan_resume.pdf
          git add de-resume.png
          git commit -m "chore: CI Automation PDF Build"
          git push origin master
     
